name: Simple Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          # Navigate to app directory
          cd /var/www/btcbot24
          
          # Pull latest changes
          git pull origin main
          
          # Install dependencies
          npm install
          
          # Build application
          npm run build:prod
          
          # Restart PM2
          npm run pm2:restart
          
          echo "Deployment completed!"